### ISSUE TITLE
Editing files with 'gum write'

### ISSUE THREAD

**Issue by cevhyruz** [charmbracelet/gum#217]
Hi! Thank you for this awesome project!

Currently there is no way to pass argument through `gum write` It would be awesome to have it like for sample a quick editing of a file without having to open vim. something like `gum write dir/dir1/file.txt`. 

Or a new command `gum edit` for that matter.

**Comment by MikaelFangel** [comment]
Hi @cevhyruz,
If you want this functionality, but won't wait for this issue to be resolved, you can get this functionality by just using bash.
```
edit="filetoedit.txt"; gum write --value "$(cat $edit)" > $edit
```

If you want a more convenient solution like the suggested, you can solve this by creating a bash wrapper for gum. Let me know if I should elaborate on this. (:

**Comment by cevhyruz** [comment]
hmm. On another note, It seems a bit dangerous.
I just lost the content of a 57 lines file while scrolling with arrow keys.

terminal spits out an error:
```
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func1()
        /home/devs/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.2-0.20221007181357-2696b2f3399f/tea.go:385 +0x95
panic({0xae6540, 0xc0000deee8})
        /usr/local/go/src/runtime/panic.go:890 +0x262
github.com/charmbracelet/bubbles/textarea.(*Model).CursorDown(0xc00012c000)
        /home/devs/go/pkg/mod/github.com/charmbracelet/bubbles@v0.14.1-0.20221006154229-d1775121146a/textarea/textarea.go:371 +0x371
github.com/charmbracelet/bubbles/textarea.Model.Update({{0x0, 0x0}, {0xc0004ee398, 0x4}, {0xc000614540, 0x12}, 0x0, 0x7e, {{{0xc00040a560, 0x2, ...}, ...}, ...}, ...}, ...)
        /home/devs/go/pkg/mod/github.com/charmbracelet/bubbles@v0.14.1-0.20221006154229-d1775121146a/textarea/textarea.go:910 +0x192c
github.com/charmbracelet/gum/write.model.Update({0x0, {0x0, 0x0}, {0xc0002e7a70, {0x0, 0x0}}, 0x0, {{0x0, 0x0}, {0xc0004ee398, ...}, ...}}, ...)
        /home/devs/go/pkg/mod/github.com/charmbracelet/gum@v0.8.0/write/write.go:54 +0x33d
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc00064a370, {0x1925060?, 0xc000524d00?}, 0x9?)
        /home/devs/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.2-0.20221007181357-2696b2f3399f/tea.go:325 +0x5ea
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc00064a370)
        /home/devs/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.2-0.20221007181357-2696b2f3399f/tea.go:450 +0x765
github.com/charmbracelet/gum/write.Options.Run({0x32, 0x5, {0x0, 0x0}, {0xc000614540, 0x12}, {0xc0004ee398, 0x4}, 0x0, 0x0, ...})
        /home/devs/go/pkg/mod/github.com/charmbracelet/gum@v0.8.0/write/command.go:55 +0x7ca
reflect.Value.call({0xaf7da0?, 0xc0004254d0?, 0xa72c65?}, {0xb0c005, 0x4}, {0xc000595b10, 0x0, 0x489e28?})
        /usr/local/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0xaf7da0?, 0xc0004254d0?, 0xabb6e0?}, {0xc000595b10?, 0xa9b0c0?, 0xc000425518?})
        /usr/local/go/src/reflect/value.go:368 +0xbc
github.com/alecthomas/kong.callMethod({0xb0a011, 0x3}, {0xaf7da0?, 0xc0004254d0?, 0x3?}, {0xaf7da0?, 0xc0004254d0?, 0x0?}, 0x0?)
        /home/devs/go/pkg/mod/github.com/alecthomas/kong@v0.6.1/callbacks.go:95 +0x549
github.com/alecthomas/kong.(*Context).RunNode(0xc000356000, 0xc00048ea50, {0x0, 0x0, 0x0})
        /home/devs/go/pkg/mod/github.com/alecthomas/kong@v0.6.1/context.go:734 +0x5f7
github.com/alecthomas/kong.(*Context).Run(0xa90e60?, {0x0?, 0xc00053ff30?, 0x7?})
        /home/devs/go/pkg/mod/github.com/alecthomas/kong@v0.6.1/context.go:759 +0x14e
main.main()
        /home/devs/go/pkg/mod/github.com/charmbracelet/gum@v0.8.0/main.go:73 +0x85c
panic: interface conversion: tea.Model is nil, not write.model

goroutine 1 [running]:
github.com/charmbracelet/gum/write.Options.Run({0x32, 0x5, {0x0, 0x0}, {0xc000614540, 0x12}, {0xc0004ee398, 0x4}, 0x0, 0x0, ...})
        /home/devs/go/pkg/mod/github.com/charmbracelet/gum@v0.8.0/write/command.go:59 +0x937
reflect.Value.call({0xaf7da0?, 0xc0004254d0?, 0xa72c65?}, {0xb0c005, 0x4}, {0xc000595b10, 0x0, 0x489e28?})
        /usr/local/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0xaf7da0?, 0xc0004254d0?, 0xabb6e0?}, {0xc000595b10?, 0xa9b0c0?, 0xc000425518?})
        /usr/local/go/src/reflect/value.go:368 +0xbc
github.com/alecthomas/kong.callMethod({0xb0a011, 0x3}, {0xaf7da0?, 0xc0004254d0?, 0x3?}, {0xaf7da0?, 0xc0004254d0?, 0x0?}, 0x0?)
        /home/devs/go/pkg/mod/github.com/alecthomas/kong@v0.6.1/callbacks.go:95 +0x549
github.com/alecthomas/kong.(*Context).RunNode(0xc000356000, 0xc00048ea50, {0x0, 0x0, 0x0})
        /home/devs/go/pkg/mod/github.com/alecthomas/kong@v0.6.1/context.go:734 +0x5f7
github.com/alecthomas/kong.(*Context).Run(0xa90e60?, {0x0?, 0xc00053ff30?, 0x7?})
        /home/devs/go/pkg/mod/github.com/alecthomas/kong@v0.6.1/context.go:759 +0x14e
main.main()
        /home/devs/go/pkg/mod/github.com/charmbracelet/gum@v0.8.0/main.go:73 +0x85c
^[[B
```
and the file contents was changed to this:
```
Caught panic:

runtime error: index out of range [17] with length 17

Restoring terminal...
```

**Comment by MikaelFangel** [comment]
Sorry to hear, appears to be some bug. Will try to see if I can replicate.

**Comment by MikaelFangel** [comment]
@cevhyruz I think I found what caused the bug and have submitted the issue #295 describing it. 

I know this is a bit hacky, but again this should take the breaking CRLF line terminators into account.
```
edit="filetoedit.txt"; gum write --value "$(cat $edit | tr -d '\r')" > $edit
```
But on the other hand, I don't know if there are other bugs hiding, so this might still be an unstable solution.

**Comment by cevhyruz** [comment]
> Sorry to hear, appears to be some bug. Will try to see if I can replicate.

No worries, that was just a random text file after all :)

**Comment by caarlos0** [comment]
you should be able to `gum write < file` or `command | gum write` now! (on main).

thanks!
