### ISSUE TITLE
One lined .csv-files crashes gum table

### ISSUE THREAD

**Issue by MikaelFangel** [charmbracelet/gum#304]
**Describe the bug**
When running `gum table` on a file containing only one line, pressing enter causes out of bounds memory access and thus crashes the program.

**To Reproduce**
1. `gum table <<< "a"`
2. press `enter`

**Expected behavior**
Gum doesn't crash and prints and empty selection, as no lines can be selected in a header only .csv-file.

**Desktop:**
 - OS: Arch 6.2.2-arch1-1

**Additional context**
Error produced
```
Caught panic:

runtime error: index out of range [0] with length 0

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/build/gum/src/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.1/tea.go:383 +0x95
panic({0x56040ce77fc0, 0xc0000b5488})
	/usr/lib/go/src/runtime/panic.go:890 +0x262
github.com/charmbracelet/bubbles/table.Model.SelectedRow(...)
	/build/gum/src/pkg/mod/github.com/charmbracelet/bubbles@v0.14.1-0.20221006154229-d1775121146a/table/table.go:257
github.com/charmbracelet/gum/table.model.Update({{{{{...}, {...}, 0x0}, {{...}, {...}, 0x0}, {{...}, {...}, 0x0}, {{...}, ...}, ...}, ...}, ...}, ...)
	/build/gum/src/gum/table/table.go:39 +0x405
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000982370, {0x56040ce9f848?, 0xc000126f00?}, 0x7f1c030000008a3b?)
	/build/gum/src/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.1/tea.go:324 +0x60a
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000982370)
	/build/gum/src/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.1/tea.go:446 +0x7fe
github.com/charmbracelet/gum/table.Options.Run({{0x56040d207b20, 0x1}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0xa, {{0x0, ...}, ...}, ...})
	/build/gum/src/gum/table/command.go:96 +0xc0a
reflect.Value.call({0x56040ce80200?, 0xc000415370?, 0x56040ce03ded?}, {0x56040bfd7aaa, 0x4}, {0xc00057db10, 0x0, 0x56040b9e58c8?})
	/usr/lib/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0x56040ce80200?, 0xc000415370?, 0x56040ce4d0a0?}, {0xc00057db10?, 0x10?, 0xc0005c0800?})
	/usr/lib/go/src/reflect/value.go:368 +0xbc
github.com/alecthomas/kong.callMethod({0x56040bfd5ab2, 0x3}, {0x56040ce80200?, 0xc000415370?, 0x3?}, {0x56040ce80200?, 0xc000415370?, 0x0?}, 0x0?)
	/build/gum/src/pkg/mod/github.com/alecthomas/kong@v0.7.1/callbacks.go:95 +0x549
github.com/alecthomas/kong.(*Context).RunNode(0xc000362100, 0xc000486e10, {0x0, 0x0, 0x0})
	/build/gum/src/pkg/mod/github.com/alecthomas/kong@v0.7.1/context.go:755 +0x5f7
github.com/alecthomas/kong.(*Context).Run(0x56040ce22180?, {0x0?, 0xc00055ff30?, 0x7?})
	/build/gum/src/pkg/mod/github.com/alecthomas/kong@v0.7.1/context.go:780 +0x14e
main.main()
	/build/gum/src/gum/main.go:73 +0x85c
failed to get selection
```

**Comment by MikaelFangel** [comment]
Have done some debugging already and the bug originates in the bubbles/table module. (;
