### ISSUE TITLE
gum table crash

### ISSUE THREAD

**Issue by Justinzobel** [charmbracelet/gum#766]
```
/gum_0.14.5_Linux_x86_64/gum table < /tmp/test
 Bubble Gum Flavor  Price 
Caught panic:

runtime error: slice bounds out of range [2:1]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.23.1/x64/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.23.1/x64/src/runtime/debug/stack.go:18 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.0/tea.go:519 +0x8b
panic({0xa0e8c0?, 0xc000712090?})
        /opt/hostedtoolcache/go/1.23.1/x64/src/runtime/panic.go:785 +0x132
github.com/charmbracelet/bubbles/viewport.Model.visibleLines(...)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.20.0/viewport/viewport.go:123
github.com/charmbracelet/bubbles/viewport.(*Model).GotoBottom(0x0?)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.20.0/viewport/viewport.go:237 +0x19f
github.com/charmbracelet/bubbles/viewport.(*Model).SetContent(0xc000746b50, {0x0?, 0x9ad040?})
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.20.0/viewport/viewport.go:107 +0xb1
github.com/charmbracelet/bubbles/table.(*Model).UpdateViewport(0xc000745340)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.20.0/table/table.go:282 +0x1b2
github.com/charmbracelet/bubbles/table.(*Model).MoveDown(0xc000745340, 0x1)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.20.0/table/table.go:371 +0x65
github.com/charmbracelet/bubbles/table.Model.Update({{{{0xc000650e80, 0x2, 0x2}, {{...}, {...}}, 0x0}, {{0xc000650ea0, 0x2, 0x2}, {{...}, ...}, ...}, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.20.0/table/table.go:213 +0x227
github.com/charmbracelet/gum/table.model.Update({{{{{...}, {...}, 0x0}, {{...}, {...}, 0x0}, {{...}, {...}, 0x0}, {{...}, ...}, ...}, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/charmbracelet/gum@v0.14.5/table/table.go:48 +0x2c5
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000895200, {0x13da3c0?, 0xc000670008?}, 0xc000956700)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.0/tea.go:452 +0x810
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000895200)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.0/tea.go:593 +0xa32
github.com/charmbracelet/gum/table.Options.Run({{0x16c07c0, 0x1}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, 0x0, ...})
        /home/runner/go/pkg/mod/github.com/charmbracelet/gum@v0.14.5/table/command.go:113 +0x1005
reflect.Value.call({0xa1bdc0?, 0xc000491840?, 0x10?}, {0xa3cf06, 0x4}, {0xc0001138f8, 0x0, 0x97ed28?})
        /opt/hostedtoolcache/go/1.23.1/x64/src/reflect/value.go:581 +0xca6
reflect.Value.Call({0xa1bdc0?, 0xc000491840?, 0x9d7960?}, {0xc0001138f8?, 0x0?, 0x0?})
        /opt/hostedtoolcache/go/1.23.1/x64/src/reflect/value.go:365 +0xb9
github.com/alecthomas/kong.callFunction({0xa1bdc0?, 0xc000491840?, 0xc000113ad0?}, 0xc000717b60)
        /home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.9.0/callbacks.go:98 +0x45a
github.com/alecthomas/kong.(*Context).RunNode(0xc00030e000, 0xc0003d3950, {0x0, 0x0, 0xc00030ac80?})
        /home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.9.0/context.go:774 +0x7ee
github.com/alecthomas/kong.(*Context).Run(0x99e240?, {0x0?, 0xc0005f9ee0?, 0x7?})
        /home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.9.0/context.go:799 +0x132
main.main()
        /home/runner/go/pkg/mod/github.com/charmbracelet/gum@v0.14.5/main.go:75 +0x885
failed to get selection
```

It displays the header but that's it. This is the example.csv taken from the table folder in the repo. It shows no other rows and crashes when you try move up/down with the up/down arrow keys on keyboard. If I press enter without trying to remove it will return the first result of `Strawberry,$0.99`

**Comment by caarlos0** [comment]
this is fixed on main. you can workaround it for now by giving it a height (e.g. `--height 10`).

**Comment by meleu** [comment]
Is there any ETA for a new release with this fix?

**Comment by meowgorithm** [comment]
We're planning on early January 2025.
